# Generated by Django 2.1.15 on 2024-05-05 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('alarmType', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('severity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='canInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleBattery', models.BigIntegerField()),
                ('AMinCellVolt', models.BigIntegerField()),
                ('stateOfCharge', models.BigIntegerField()),
                ('APackVoltageValue', models.BigIntegerField()),
                ('APackCurrentValue', models.BigIntegerField()),
                ('batteryTemperature', models.BigIntegerField()),
                ('ASOCValue', models.BigIntegerField()),
                ('BFaultRank', models.BigIntegerField()),
                ('totalRegenerationEnergy', models.BigIntegerField()),
                ('BPackCurrentValue', models.BigIntegerField()),
                ('BMaxCellVolt', models.BigIntegerField()),
                ('ChargerGunDetected2', models.BigIntegerField()),
                ('AMaxCellVolt', models.BigIntegerField()),
                ('BMinCellVolt', models.BigIntegerField()),
                ('BPackVoltageValue', models.BigIntegerField()),
                ('AFaultRank', models.BigIntegerField()),
                ('BSOCValue', models.BigIntegerField()),
                ('distanceToEmpty', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='deviceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpsTime', models.BigIntegerField()),
                ('gprsTime', models.BigIntegerField()),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
                ('altitude', models.IntegerField()),
                ('heading', models.IntegerField()),
                ('speedKph', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('odometer', models.BigIntegerField()),
                ('gpsSignal', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('registrationNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('deviceType', models.CharField(blank=True, max_length=255, null=True)),
                ('chassisNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('trackingCode', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dinputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_1', models.IntegerField(null=True)),
                ('input_2', models.IntegerField(null=True)),
                ('input_3', models.IntegerField(null=True)),
                ('input_4', models.IntegerField(null=True)),
                ('input_5', models.IntegerField(null=True)),
                ('input_6', models.IntegerField(null=True)),
                ('input_7', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedUrl', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_links', to='database.devices')),
            ],
        ),
        migrations.CreateModel(
            name='todaysDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todayKms', models.IntegerField()),
                ('todayMovementTime', models.IntegerField()),
                ('todayIdleTime', models.IntegerField()),
                ('todayDriveCount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_todaysDrive', to='database.devices')),
            ],
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviceLocation', to='database.devices'),
        ),
        migrations.AddField(
            model_name='caninfo',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canInfo_devices', to='database.devices'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_alerts', to='database.devices'),
        ),
    ]
