# Generated by Django 5.0.4 on 2024-05-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_alerts_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='alarmType',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='latitude',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='longitude',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='severity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='timestamp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todaysdrive',
            name='todayDriveCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todaysdrive',
            name='todayIdleTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todaysdrive',
            name='todayKms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todaysdrive',
            name='todayMovementTime',
            field=models.IntegerField(null=True),
        ),
    ]
