# Generated by Django 5.0.4 on 2024-05-05 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_alerts_alarmtype_alter_alerts_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
