# Generated by Django 5.0.4 on 2024-05-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_devicestatus_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='name',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='registrationNumber',
        ),
    ]
