# Generated by Django 5.0.4 on 2024-05-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_devices_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='registrationNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
