# Generated by Django 5.0.4 on 2024-05-11 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_devices_name_devices_registrationnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_alerts', to='database.devices'),
        ),
        migrations.AlterField(
            model_name='caninfo',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canInfo_devices', to='database.devices'),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviceLocation', to='database.devices'),
        ),
    ]
