# Generated by Django 5.0.4 on 2024-05-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alerts_transactionid_caninfo_transactionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caninfo',
            name='stateOfCharge',
            field=models.IntegerField(null=True),
        ),
    ]
