# Generated by Django 5.0.4 on 2024-05-15 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_caninfo_stateofcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinputs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 12, 13, 35, 313371)),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 12, 13, 35, 312372)),
        ),
        migrations.AlterField(
            model_name='caninfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 12, 13, 35, 311426)),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 12, 13, 35, 310372)),
        ),
        migrations.AlterField(
            model_name='devices',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 12, 13, 35, 309375)),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 12, 13, 35, 310372)),
        ),
        migrations.AlterField(
            model_name='links',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 12, 13, 35, 313371)),
        ),
        migrations.AlterField(
            model_name='todaysdrive',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 12, 13, 35, 312372)),
        ),
    ]
